### ISSUE TITLE
Move lynxmotion_ssc32 to smd-ros-pkg and release it

### ISSUE THREAD

**Issue by cottsay** [smd-ros-devel/lynxmotion_ssc32#6]
I think we should move this driver to `smd-ros-pkg` and officially release it.

Thoughts from @mattrichard? @tonybaltovski?

**Comment by tonybaltovski** [comment]
I agree, good idea.  I have been noticing more and more people using it.  Have you guys used this with a C++ publisher?

**Comment by mattrichard** [comment]
I also support the idea. I think I'll spend the rest of this week adding a few more features and cleaning up some of the code. Then this weekend I'll release it. @cottsay, you have experience releasing packages, right? I may need some help with that.

**Comment by mattrichard** [comment]
With the revival of this package and many things changing over the years between ROS 1 and 2, I'm going to hold of on making any releases anytime soon.

Once the ROS 2 port is ready I'll work with cottsay to see how this can be officially released as a ROS 2 package, if it makes sense to do it in the first place.

Closing this issue for now.
